name: ci

on:
  release:
    types: [published]

jobs:
  publish:
    name: publish 
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build
      run: dotnet build -c Release /p:version=${{ github.event.release.tag_name }}

    - name: Test
      run: dotnet test -c Release
      
    - name: Publish to NuGet
      run: dotnet nuget push src\SpecFirst\bin\Release\*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
